apiVersion: v1
kind: Service
metadata:
  name: fastpass-worker
  namespace: fastpass
  labels:
    app: fastpass-worker
spec:
  type: ClusterIP
  selector:
    app: fastpass-worker
  ports:
    - name: http
      port: 8080
      targetPort: 8080