namespace: fastpass

image:
  repository: ghcr.io/kdh8128/fastpass-k8s-api
  tag: 8a612e8dfe9794b25155ab6b969a36e735cd1db1
  pullPolicy: IfNotPresent

api:
  replicas: 1
  port: 8080
  workerEnabled: false

worker:
  replicas: 1
  port: 8080
  workerEnabled: true

postgres:
  image: postgres:16
  database: fastpass
  username: fastpass
  password: fastpass
  port: 5432
  storage: 1Gi

redis:
  image: redis:7.2-alpine
  port: 6379

resources:
  api:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      cpu: 500m
      memory: 768Mi
  worker:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      cpu: 500m
      memory: 768Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 6
  cpuAverageUtilization: 60

monitoring:
  enabled: true
  namespace: monitoring
  releaseLabel: prometheus-stack

alerting:
  enabled: true
  queueBacklogThreshold: 50
