spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fastpass
    driver-class-name: org.postgresql.Driver
    username: fastpass
    password: fastpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
