server:
  port: 8080

spring:
  application:
    name: fastpass-api

  datasource:
    url: jdbc:h2:mem:fastpassdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics